apiVersion: v1
kind: Pod
metadata: 
  name: pod-nginx
  namespace: updeshargocd  
  labels: 
    app: pod
spec:
  containers: 
    - name: nginx-con
      image: nginx:latest
      ports:
        - containerPort: 80